// countries.js - Volledige database met alle 48 landen + FWC sectie
const collections = [
    { prefix: 'FWC', name: 'FIFA World Cup Special', count: 20, flagUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo_de_la_Copa_Mundial_de_f%C3%BAtbol_2026.svg/200px-Logo_de_la_Copa_Mundial_de_f%C3%BAtbol_2026.svg.png' },
    { prefix: 'USA', name: 'Verenigde Staten', count: 20, flagUrl: 'https://flagcdn.com/w160/us.png' },
    { prefix: 'MEX', name: 'Mexico', count: 20, flagUrl: 'https://flagcdn.com/w160/mx.png' },
    { prefix: 'CAN', name: 'Canada', count: 20, flagUrl: 'https://flagcdn.com/w160/ca.png' },
    { prefix: 'ARG', name: 'Argentinië', count: 20, flagUrl: 'https://flagcdn.com/w160/ar.png' },
    { prefix: 'BEL', name: 'België', count: 20, flagUrl: 'https://flagcdn.com/w160/be.png' },
    { prefix: 'BRA', name: 'Brazilië', count: 20, flagUrl: 'https://flagcdn.com/w160/br.png' },
    { prefix: 'FRA', name: 'Frankrijk', count: 20, flagUrl: 'https://flagcdn.com/w160/fr.png' },
    { prefix: 'ENG', name: 'Engeland', count: 20, flagUrl: 'https://flagcdn.com/w160/gb-eng.png' },
    { prefix: 'ESP', name: 'Spanje', count: 20, flagUrl: 'https://flagcdn.com/w160/es.png' },
    { prefix: 'GER', name: 'Duitsland', count: 20, flagUrl: 'https://flagcdn.com/w160/de.png' },
    { prefix: 'ITA', name: 'Italië', count: 20, flagUrl: 'https://flagcdn.com/w160/it.png' },
    { prefix: 'NED', name: 'Nederland', count: 20, flagUrl: 'https://flagcdn.com/w160/nl.png' },
    { prefix: 'POR', name: 'Portugal', count: 20, flagUrl: 'https://flagcdn.com/w160/pt.png' },
    { prefix: 'CRO', name: 'Kroatië', count: 20, flagUrl: 'https://flagcdn.com/w160/hr.png' },
    { prefix: 'MAR', name: 'Marokko', count: 20, flagUrl: 'https://flagcdn.com/w160/ma.png' },
    { prefix: 'JPN', name: 'Japan', count: 20, flagUrl: 'https://flagcdn.com/w160/jp.png' },
    { prefix: 'KOR', name: 'Zuid-Korea', count: 20, flagUrl: 'https://flagcdn.com/w160/kr.png' },
    { prefix: 'COL', name: 'Colombia', count: 20, flagUrl: 'https://flagcdn.com/w160/co.png' },
    { prefix: 'URU', name: 'Uruguay', count: 20, flagUrl: 'https://flagcdn.com/w160/uy.png' },
    { prefix: 'SEN', name: 'Senegal', count: 20, flagUrl: 'https://flagcdn.com/w160/sn.png' },
    { prefix: 'NGA', name: 'Nigeria', count: 20, flagUrl: 'https://flagcdn.com/w160/ng.png' },
    { prefix: 'CMR', name: 'Kameroen', count: 20, flagUrl: 'https://flagcdn.com/w160/cm.png' },
    { prefix: 'GHA', name: 'Ghana', count: 20, flagUrl: 'https://flagcdn.com/w160/gh.png' },
    { prefix: 'CIV', name: 'Ivoorkust', count: 20, flagUrl: 'https://flagcdn.com/w160/ci.png' },
    { prefix: 'ALG', name: 'Algerije', count: 20, flagUrl: 'https://flagcdn.com/w160/al.png' },
    { prefix: 'EGY', name: 'Egypte', count: 20, flagUrl: 'https://flagcdn.com/w160/eg.png' },
    { prefix: 'TUN', name: 'Tunesië', count: 20, flagUrl: 'https://flagcdn.com/w160/tn.png' },
    { prefix: 'RSA', name: 'Zuid-Afrika', count: 20, flagUrl: 'https://flagcdn.com/w160/za.png' },
    { prefix: 'COD', name: 'Congo DR', count: 20, flagUrl: 'https://flagcdn.com/w160/cd.png' },
    { prefix: 'KSA', name: 'Saoedi-Arabië', count: 20, flagUrl: 'https://flagcdn.com/w160/sa.png' },
    { prefix: 'QAT', name: 'Qatar', count: 20, flagUrl: 'https://flagcdn.com/w160/qa.png' },
    { prefix: 'IRN', name: 'Iran', count: 20, flagUrl: 'https://flagcdn.com/w160/ir.png' },
    { prefix: 'IRQ', name: 'Irak', count: 20, flagUrl: 'https://flagcdn.com/w160/iq.png' },
    { prefix: 'UAE', name: 'Verenigde Arabische Emiraten', count: 20, flagUrl: 'https://flagcdn.com/w160/ae.png' },
    { prefix: 'AUS', name: 'Australië', count: 20, flagUrl: 'https://flagcdn.com/w160/au.png' },
    { prefix: 'NZL', name: 'Nieuw-Zeeland', count: 20, flagUrl: 'https://flagcdn.com/w160/nz.png' },
    { prefix: 'PAN', name: 'Panama', count: 20, flagUrl: 'https://flagcdn.com/w160/pa.png' },
    { prefix: 'CRC', name: 'Costa Rica', count: 20, flagUrl: 'https://flagcdn.com/w160/cr.png' },
    { prefix: 'JAM', name: 'Jamaica', count: 20, flagUrl: 'https://flagcdn.com/w160/jm.png' },
    { prefix: 'ECU', name: 'Ecuador', count: 20, flagUrl: 'https://flagcdn.com/w160/ec.png' },
    { prefix: 'PER', name: 'Peru', count: 20, flagUrl: 'https://flagcdn.com/w160/pe.png' },
    { prefix: 'CHI', name: 'Chili', count: 20, flagUrl: 'https://flagcdn.com/w160/cl.png' },
    { prefix: 'PAR', name: 'Paraguay', count: 20, flagUrl: 'https://flagcdn.com/w160/py.png' },
    { prefix: 'VEN', name: 'Venezuela', count: 20, flagUrl: 'https://flagcdn.com/w160/ve.png' },
    { prefix: 'UKR', name: 'Oekraïne', count: 20, flagUrl: 'https://flagcdn.com/w160/ua.png' },
    { prefix: 'TUR', name: 'Turkije', count: 20, flagUrl: 'https://flagcdn.com/w160/tr.png' },
    { prefix: 'SUI', name: 'Zwitserland', count: 20, flagUrl: 'https://flagcdn.com/w160/ch.png' },
    { prefix: 'AUT', name: 'Oostenrijk', count: 20, flagUrl: 'https://flagcdn.com/w160/at.png' }
];
