// countries.js - Het officiële en definitieve WK 2026 Database (Pagina's 100% Gefixt!)

const collections = [
    { 
        prefix: 'FWC', name: 'FIFA World Cup', count: 20, page: '2-5 & 106-109',
        flagUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo_de_la_Copa_Mundial_de_f%C3%BAtbol_2026.svg/200px-Logo_de_la_Copa_Mundial_de_f%C3%BAtbol_2026.svg.png', 
        colors: ['#4f46e5', '#ff005b'], group: 'Introductie',
        players: [
            "Panini Logo (00)", "Official Emblem 1", "Official Emblem 2", "Official Mascots", "Official Slogan", 
            "Official Match Ball", "Host Canada", "Host Mexico", "Host USA", 
            "1930 Uruguay", "1934 Italy", "1950 Brazil", "1954 Switzerland", 
            "1958 Sweden", "1962 Chile", "1966 England", "1970 Mexico", 
            "1974 Germany", "1978 Argentina", "1982 Italy"
        ] 
    },
    
    // POULE A
    { prefix: 'MEX', name: 'Mexico', count: 20, page: '8-9', flagUrl: 'https://flagcdn.com/w160/mx.png', colors: ['#006847', '#CE1126'], group: 'Poule A', players: ["Team Logo (Foil)", "Luis Malagón", "Johan Vásquez", "Jorge Sánchez", "César Montes", "Gerardo Arteaga", "Israel Reyes", "Diego Lainez", "Carlos Rodríguez", "Edson Álvarez", "Orbelín Pineda", "Marcel Ruiz", "Teamfoto (MEX)", "Érick Sánchez", "Hirving Lozano", "Santiago Giménez", "Raúl Jiménez", "Alexis Vega", "Roberto Alvarado", "César Huerta"] },
    { prefix: 'RSA', name: 'Zuid-Afrika', count: 20, page: '10-11', flagUrl: 'https://flagcdn.com/w160/za.png', colors: ['#007749', '#FFB81C'], group: 'Poule A', players: ["Team Logo (Foil)", "Ronwen Williams", "Sipho Chaine", "Aubrey Modiba", "Siyanda Xulu", "Mothobi Mvala", "Khuliso Mudau", "Siyabonga Ngezana", "Grant Kekana", "Nkosinathi Sibisi", "Teboho Mokoena", "Thalente Mbatha", "Teamfoto (RSA)", "Bathusi Aubaas", "Themba Zwane", "Sipho Mbule", "Lyle Foster", "Iqraam Rayners", "Mihlali Mayambela", "Oswin Appollis"] },
    { prefix: 'KOR', name: 'Zuid-Korea', count: 20, page: '12-13', flagUrl: 'https://flagcdn.com/w160/kr.png', colors: ['#CD2E3A', '#0047A0'], group: 'Poule A', players: ["Team Logo (Foil)", "Jo Hyeonwoo", "Kim Seunggyu", "Kim Minjae", "Cho Yumin", "Seol Youngwoo", "Lee Hanbeom", "Lee Taeseok", "Lee Myungjae", "Lee Jaesung", "Hwang Inbeom", "Lee Kangin", "Teamfoto (KOR)", "Paik Seungho", "Hong Hyunseok", "Lee Donggyeong", "Cho Guesung", "Son Heungmin", "Hwang Heechan", "Oh Hyeongyu"] },
    { prefix: 'CZE', name: 'Tsjechië', count: 20, page: '14-15', flagUrl: 'https://flagcdn.com/w160/cz.png', colors: ['#D7141A', '#11457E'], group: 'Poule A', players: ["Team Logo (Foil)", "Matej Kovar", "Jindrich Stanek", "Ladislav Krejci", "Vladimir Coufal", "Jaroslav Zeleny", "Tomas Holes", "David Zima", "Michal Sadilek", "Lukas Provod", "Lukas Cerv", "Tomas Soucek", "Teamfoto (CZE)", "Pavel Sulc", "Matej Vydra", "Vasil Kusej", "Tomas Chory", "Vaclav Cerny", "Adam Hlozek", "Patrik Schick"] },

    // POULE B
    { prefix: 'CAN', name: 'Canada', count: 20, page: '16-17', flagUrl: 'https://flagcdn.com/w160/ca.png', colors: ['#FF0000', '#444444'], group: 'Poule B', players: ["Team Logo (Foil)", "Dayne St. Clair", "Alphonso Davies", "Alistair Johnston", "Samuel Adekugbe", "Richie Laryea", "Derek Cornelius", "Moise Bombito", "Kamal Miller", "Stephen Eustaquio", "Ismael Kone", "Jonathan Osorio", "Teamfoto (CAN)", "Jacob Shaffelburg", "Mathieu Choiniere", "Ali Ahmed", "Tajon Buchanan", "Liam Millar", "Cyle Larin", "Jonathan David"] },
    { prefix: 'BIH', name: 'Bosnië en Her.', count: 20, page: '18-19', flagUrl: 'https://flagcdn.com/w160/ba.png', colors: ['#002395', '#FECB00'], group: 'Poule B', players: ["Team Logo (Foil)", "Nikola Vasilj", "Amar Dedic", "Sead Kolasinac", "Tarik Muharemovic", "Nihad Mujakic", "Nikola Katic", "Amir Hadziahmetovic", "Benjamin Tahirovic", "Armin Gigovic", "Dario Saric", "Ivan Basic", "Teamfoto (BIH)", "Dzenis Burnic", "Esmir Bajraktarevic", "Amar Rahmanovic", "Ermedin Demirovic", "Edin Dzeko", "Samed Bazdar", "Haris Tabakovic"] },
    { prefix: 'QAT', name: 'Qatar', count: 20, page: '20-21', flagUrl: 'https://flagcdn.com/w160/qa.png', colors: ['#8A1538', '#666666'], group: 'Poule B', players: ["Team Logo (Foil)", "Meshaal Barsham", "Sultan Al-Brake", "Lucas Mendes", "Homam Ahmed", "Boualem Khoukhi", "Pedro Miguel", "Tarek Salman", "Mohammed Muntari", "Karim Boudiaf", "Assim Madibo", "Ahmed Fatehi", "Teamfoto (QAT)", "Mohammed Waad", "Abdulaziz Hatem", "Bassam Al-Rawi", "Edmilson Junior", "Akram Afif", "Ahmed Al-Ganehi", "Almoez Ali"] },
    { prefix: 'SUI', name: 'Zwitserland', count: 20, page: '22-23', flagUrl: 'https://flagcdn.com/w160/ch.png', colors: ['#FF0000', '#333333'], group: 'Poule B', players: ["Team Logo (Foil)", "Gregor Kobel", "Yvon Mvogo", "Manuel Akanji", "Ricardo Rodriguez", "Nico Elvedi", "Aurele Amenda", "Silvan Widmer", "Granit Xhaka", "Denis Zakaria", "Remo Freuler", "Fabian Rieder", "Teamfoto (SUI)", "Ardon Jashari", "Joël Monteiro", "Michel Aebischer", "Breel Embolo", "Ruben Vargas", "Dan Ndoye", "Zeki Amdouni"] },

    // POULE C
    { prefix: 'BRA', name: 'Brazilië', count: 20, page: '24-25', flagUrl: 'https://flagcdn.com/w160/br.png', colors: ['#009739', '#FFDF00'], group: 'Poule C', players: ["Team Logo (Foil)", "Alisson", "Bento", "Marquinhos", "Eder Militao", "Gabriel Magalhaes", "Danilo", "Wendell", "Lucas Paqueta", "Casemiro", "Bruno Guimaraes", "Luiz Henrique", "Teamfoto (BRA)", "Vinicius Junior", "Rodrygo", "Joao Pedro", "Matheus Cunha", "Gabriel Martinelli", "Raphinha", "Estevao"] },
    { prefix: 'MAR', name: 'Marokko', count: 20, page: '26-27', flagUrl: 'https://flagcdn.com/w160/ma.png', colors: ['#C1272D', '#006233'], group: 'Poule C', players: ["Team Logo (Foil)", "Yassine Bounou", "Munir El Kajoui", "Achraf Hakimi", "Noussair Mazraoui", "Nayef Aguerd", "Romain Saïss", "Jawad El Yamiq", "Adam Masina", "Sofyan Amrabat", "Azzedine Ounahi", "Eliesse Ben Seghir", "Teamfoto (MAR)", "Bilal El Khannouss", "Ismael Saibari", "Youssef En-Nesyri", "Abde Ezzalzouli", "Soufiane Rahimi", "Brahim Díaz", "Ayoub El Kaabi"] },
    { prefix: 'HAI', name: 'Haïti', count: 20, page: '28-29', flagUrl: 'https://flagcdn.com/w160/ht.png', colors: ['#D21034', '#00205B'], group: 'Poule C', players: ["Team Logo (Foil)", "Johny Placide", "Carlens Arcus", "Martin Expérience", "Jean-Kévin Duverne", "Ricardo Adé", "Duke Lacroix", "Garven Metusala", "Hannes Delcroix", "Leverton Pierre", "Danley Jean Jacques", "Jean-Ricner Bellegarde", "Teamfoto (HAI)", "Christopher Attys", "Derrick Etienne Jr.", "Josué Casimir", "Ruben Providence", "Duckens Nazon", "Louicius Deedson", "Frantzdy Pierrot"] },
    { prefix: 'SCO', name: 'Schotland', count: 20, page: '30-31', flagUrl: 'https://flagcdn.com/w160/gb-sct.png', colors: ['#005EB8', '#FFFFFF'], group: 'Poule C', players: ["Team Logo (Foil)", "Angus Gunn", "Jack Hendry", "Kieran Tierney", "Aaron Hickey", "Andrew Robertson", "Scott McKenna", "John Souttar", "Anthony Ralston", "Grant Hanley", "Scott McTominay", "Billy Gilmour", "Teamfoto (SCO)", "Lewis Ferguson", "Ryan Christie", "Kenny McLean", "John McGinn", "Lyndon Dykes", "Ché Adams", "Ben Doak"] },

    // POULE D
    { prefix: 'USA', name: 'Verenigde Staten', count: 20, page: '32-33', flagUrl: 'https://flagcdn.com/w160/us.png', colors: ['#B22234', '#3C3B6E'], group: 'Poule D', players: ["Team Logo (Foil)", "Matt Freese", "Chris Richards", "Tim Ream", "Mark McKenzie", "Alex Freeman", "Antonee Robinson", "Tyler Adams", "Yunus Musah", "Weston McKennie", "Giovanni Reyna", "Timothy Weah", "Teamfoto (USA)", "Diego Luna", "Malik Tillman", "Christian Pulisic", "Brenden Aaronson", "Ricardo Pepi", "Haji Wright", "Folarin Balogun"] },
    { prefix: 'PAR', name: 'Paraguay', count: 20, page: '34-35', flagUrl: 'https://flagcdn.com/w160/py.png', colors: ['#D52B1E', '#0038A8'], group: 'Poule D', players: ["Team Logo (Foil)", "Roberto Fernández", "Orlando Gill", "Gustavo Gómez", "Fabián Balbuena", "Juan José Cáceres", "Omar Alderete", "Júnior Alonso", "Mathías Villasanti", "Diego Gómez", "Damián Bobadilla", "Andrés Cubas", "Teamfoto (PAR)", "Matías Galarza Fonda", "Julio Enciso", "Alejandro Romero Gamarra", "Miguel Almirón", "Ramón Sosa", "Ángel Romero", "Antonio Sanabria"] },
    { prefix: 'AUS', name: 'Australië', count: 20, page: '36-37', flagUrl: 'https://flagcdn.com/w160/au.png', colors: ['#FFCD00', '#008751'], group: 'Poule D', players: ["Team Logo (Foil)", "Mathew Ryan", "Joe Gauci", "Harry Souttar", "Alessandro Circati", "Jordan Bos", "Aziz Behich", "Cameron Burgess", "Lewis Miller", "Milos Degenek", "Jackson Irvine", "Riley McGree", "Teamfoto (AUS)", "Aiden O'Neill", "Connor Metcalfe", "Patrick Yazbek", "Craig Goodwin", "Kusini Yengi", "Nestory Irankunda", "Mohamed Toure"] },
    { prefix: 'TUR', name: 'Turkije', count: 20, page: '38-39', flagUrl: 'https://flagcdn.com/w160/tr.png', colors: ['#E30A17', '#222222'], group: 'Poule D', players: ["Team Logo (Foil)", "Uğurcan Çakır", "Mert Müldür", "Zeki Çelik", "Abdülkerim Bardakcı", "Çağlar Söyüncü", "Merih Demiral", "Ferdi Kadıoğlu", "Kaan Ayhan", "İsmail Yüksek", "İrfan Can Kahveci", "Orkun Kökçü", "Teamfoto (TUR)", "Arda Güler", "Hakan Çalhanoğlu", "Yunus Akgün", "Cenk Tosun", "Barış Alper Yılmaz", "Kerem Aktürkoğlu", "Kenan Yıldız"] },

    // POULE E
    { prefix: 'GER', name: 'Duitsland', count: 20, page: '40-41', flagUrl: 'https://flagcdn.com/w160/de.png', colors: ['#222222', '#FFCE00'], group: 'Poule E', players: ["Team Logo (Foil)", "Marc-André ter Stegen", "Jonathan Tah", "David Raum", "Nico Schlotterbeck", "Antonio Rüdiger", "Waldemar Anton", "Ridle Baku", "Maximilian Mittelstädt", "Joshua Kimmich", "Florian Wirtz", "Felix Nmecha", "Teamfoto (GER)", "Leon Goretzka", "Jamal Musiala", "Serge Gnabry", "Kai Havertz", "Leroy Sané", "Karim Adeyemi", "Nick Woltemade"] },
    { prefix: 'CIV', name: 'Ivoorkust', count: 20, page: '44-45', flagUrl: 'https://flagcdn.com/w160/ci.png', colors: ['#F77F00', '#009E60'], group: 'Poule E', players: ["Team Logo (Foil)", "Yahia Fofana", "Ghislain Konan", "Wilfried Singo", "Odilon Kossounou", "Evan Ndicka", "Willy Boly", "Emmanuel Agbadou", "Ousmane Diomande", "Franck Kessié", "Seko Fofana", "Ibrahim Sangaré", "Teamfoto (CIV)", "Jean-Philippe Gbamin", "Amad Diallo", "Sébastien Haller", "Simon Adingra", "Yan Diomande", "Evann Guessand", "Oumar Diakité"] },
    { prefix: 'CUW', name: 'Curaçao', count: 20, page: '42-43', flagUrl: 'https://flagcdn.com/w160/cw.png', colors: ['#002B7F', '#F9E814'], group: 'Poule E', players: ["Team Logo (Foil)", "Eloy Room", "Armando Obispo", "Sherel Floranus", "Juriën Gaari", "Joshua Brenet", "Roshon van Eijma", "Shurandy Sambo", "Livano Comenencia", "Godfried Roemeratoe", "Juninho Bacuna", "Leandro Bacuna", "Teamfoto (CUW)", "Tahith Chong", "Kenji Gorré", "Jearl Margaritha", "Jürgen Locadia", "Jeremy Antonisse", "Gervane Kastaneer", "Boye Hansen"] },
    { prefix: 'ECU', name: 'Ecuador', count: 20, page: '46-47', flagUrl: 'https://flagcdn.com/w160/ec.png', colors: ['#FFD100', '#00205B'], group: 'Poule E', players: ["Team Logo (Foil)", "Hernán Galíndez", "Gonzalo Valle", "Piero Hincapié", "Pervis Estupiñán", "Willian Pacho", "Angelo Preciado", "Joel Ordóñez", "Moisés Caicedo", "Alan Franco", "Kendry Páez", "Pedro Vite", "Teamfoto (ECU)", "John Yeboah", "Leonardo Campana", "Gonzalo Plata", "Nilson Angulo", "Alan Minda", "Kevin Rodríguez", "Enner Valencia"] },

    // POULE F
    { prefix: 'NED', name: 'Nederland', count: 20, page: '48-49', flagUrl: 'https://flagcdn.com/w160/nl.png', colors: ['#F36C21', '#21468B'], group: 'Poule F', players: ["Team Logo (Foil)", "Bart Verbruggen", "Virgil van Dijk", "Micky van de Ven", "Jurriën Timber", "Denzel Dumfries", "Nathan Aké", "Jeremie Frimpong", "Jan Paul van Hecke", "Tijjani Reijnders", "Ryan Gravenberch", "Teun Koopmeiners", "Teamfoto (NED)", "Frenkie de Jong", "Xavi Simons", "Justin Kluivert", "Memphis Depay", "Donyell Malen", "Wout Weghorst", "Cody Gakpo"] },
    { prefix: 'JPN', name: 'Japan', count: 20, page: '50-51', flagUrl: 'https://flagcdn.com/w160/jp.png', colors: ['#000555', '#BC002D'], group: 'Poule F', players: ["Team Logo (Foil)", "Zion Suzuki", "Henry Heroki Mochizuki", "Ayumu Seko", "Yukinari Sugawara", "Shogo Taniguchi", "Tsuyoshi Watanabe", "Kaishu Sano", "Yuki Soma", "Ao Tanaka", "Daichi Kamada", "Takefusa Kubo", "Teamfoto (JPN)", "Ritsu Doan", "Keito Nakamura", "Takumi Minamino", "Shuto Machino", "Junya Ito", "Koki Ogawa", "Ayase Ueda"] },
    { prefix: 'SWE', name: 'Zweden', count: 20, page: '52-53', flagUrl: 'https://flagcdn.com/w160/se.png', colors: ['#004B87', '#FFCD00'], group: 'Poule F', players: ["Team Logo (Foil)", "Viktor Johansson", "Isak Hien", "Gabriel Gudmundsson", "Emil Holm", "Victor Nilsson Lindelöf", "Gustaf Lagerbielke", "Lucas Bergvall", "Hugo Larsson", "Jesper Karlström", "Yasin Ayari", "Mattias Svanberg", "Teamfoto (SWE)", "Emil Forsberg", "Ken Sema", "Roony Bardghji", "Dejan Kulusevski", "Anthony Elanga", "Alexander Isak", "Viktor Gyökeres"] },
    { prefix: 'TUN', name: 'Tunesië', count: 20, page: '54-55', flagUrl: 'https://flagcdn.com/w160/tn.png', colors: ['#E70013', '#444444'], group: 'Poule F', players: ["Team Logo (Foil)", "Bechir Ben Said", "Aymen Dahmen", "Yan Valery", "Montassar Talbi", "Youssef Msakni", "Ali Abdi", "Dylan Bronn", "Ellyes Skhiri", "Aïssa Laïdouni", "Ferjani Sassi", "Mohamed Ali Ben Romdhane", "Teamfoto (TUN)", "Hannibal Mejbri", "Elias Achouri", "Elias Saad", "Hamza Mastouri", "Firas Ben Larbi", "Sayfallah Ltaief", "Naim Sliti"] },

    // POULE G
    { prefix: 'BEL', name: 'België', count: 20, page: '58-59', flagUrl: 'https://flagcdn.com/w160/be.png', colors: ['#ED2939', '#FDDA24'], group: 'Poule G', players: ["Team Logo (Foil)", "Thibaut Courtois", "Arthur Theate", "Timothy Castagne", "Zeno Debast", "Brandon Mechele", "Maxim De Cuyper", "Thomas Meunier", "Youri Tielemans", "Amadou Onana", "Nicolas Raskin", "Alexis Saelemaekers", "Teamfoto (BEL)", "Hans Vanaken", "Kevin De Bruyne", "Jérémy Doku", "Charles De Ketelaere", "Leandro Trossard", "Loïs Openda", "Romelu Lukaku"] },
    { prefix: 'EGY', name: 'Egypte', count: 20, page: '60-61', flagUrl: 'https://flagcdn.com/w160/eg.png', colors: ['#CE1126', '#111111'], group: 'Poule G', players: ["Team Logo (Foil)", "Mohamed El Shenawy", "Mohamed Hany", "Mohamed Hamdy", "Yasser Ibrahim", "Khaled Sobhi", "Ramy Rabia", "Hossam Abdelmaguid", "Ahmed Fatouh", "Marwan Attia", "Zizo", "Hamdi Fathi", "Teamfoto (EGY)", "Mohanad Lasheen", "Emam Ashour", "Osama Faisal", "Mohamed Salah", "Mostafa Mohamed", "Trezeguet", "Omar Marmoush"] },
    { prefix: 'IRN', name: 'Iran', count: 20, page: '62-63', flagUrl: 'https://flagcdn.com/w160/ir.png', colors: ['#239F40', '#DA0000'], group: 'Poule G', players: ["Team Logo (Foil)", "Alireza Beiranvand", "Morteza Pouraliganji", "Ehsan Hajsafi", "Milad Mohammadi", "Shojae Khalilzadeh", "Ramin Rezaeian", "Hossein Kanaanizadegan", "Sadegh Moharrami", "Saleh Hardani", "Saeid Ezatolahi", "Saman Ghoddos", "Teamfoto (IRN)", "Omid Noorafkan", "Roozbeh Cheshmi", "Mohammad Mohebi", "Sardar Azmoun", "Mehdi Taremi", "Alireza Jahanbakhsh", "Ali Gholizadeh"] },
    { prefix: 'NZL', name: 'Nieuw-Zeeland', count: 20, page: '64-65', flagUrl: 'https://flagcdn.com/w160/nz.png', colors: ['#111111', '#888888'], group: 'Poule G', players: ["Team Logo (Foil)", "Max Crocombe", "Alex Paulsen", "Michael Boxall", "Liberato Cacace", "Tim Payne", "Tyler Bindon", "Nando Pijnaker", "Finn Surman", "Joe Bell", "Sarpreet Singh", "Ryan Thomas", "Teamfoto (NZL)", "Matthew Garbett", "Marko Stamenic", "Ben Old", "Chris Wood", "Elijah Just", "Callum McCowatt", "Kosta Barbarouses"] },

    // POULE H
    { prefix: 'ESP', name: 'Spanje', count: 20, page: '66-67', flagUrl: 'https://flagcdn.com/w160/es.png', colors: ['#AA151B', '#F1BF00'], group: 'Poule H', players: ["Team Logo (Foil)", "Unai Simón", "Robin Le Normand", "Aymeric Laporte", "Dean Huijsen", "Pedro Porro", "Dani Carvajal", "Marc Cucurella", "Martín Zubimendi", "Pedri", "Rodri", "Fabián Ruiz", "Teamfoto (ESP)", "Mikel Merino", "Lamine Yamal", "Dani Olmo", "Nico Williams", "Ferran Torres", "Álvaro Morata", "Mikel Oyarzabal"] },
    { prefix: 'URU', name: 'Uruguay', count: 20, page: '72-73', flagUrl: 'https://flagcdn.com/w160/uy.png', colors: ['#0081C8', '#FCD116'], group: 'Poule H', players: ["Team Logo (Foil)", "Sergio Rochet", "Santiago Mele", "Ronald Araújo", "José María Giménez", "Sebastián Cáceres", "Mathías Olivera", "Guillermo Varela", "Nahitan Nández", "Federico Valverde", "Giorgian De Arrascaeta", "Rodrigo Bentancur", "Teamfoto (URU)", "Manuel Ugarte", "Nicolás De La Cruz", "Maxi Araújo", "Darwin Núñez", "Federico Viñas", "Rodrigo Aguirre", "Facundo Pellistri"] },
    { prefix: 'CPV', name: 'Kaapverdië', count: 20, page: '68-69', flagUrl: 'https://flagcdn.com/w160/cv.png', colors: ['#003893', '#CF2027'], group: 'Poule H', players: ["Team Logo (Foil)", "Vozinha", "Logan Costa", "Pico", "Diney", "Steven Moreira", "Wagner Pina", "João Paulo", "Yannick Semedo", "Kevin Pina", "Patrick Andrade", "Jamiro Monteiro", "Teamfoto (CPV)", "Deroy Duarte", "Garry Rodrigues", "Jovane Cabral", "Ryan Mendes", "Dailon Livramento", "Willy Semedo", "Bebé"] },
    { prefix: 'KSA', name: 'Saoedi-Arabië', count: 20, page: '70-71', flagUrl: 'https://flagcdn.com/w160/sa.png', colors: ['#006C35', '#D4AF37'], group: 'Poule H', players: ["Team Logo (Foil)", "Nawaf Alaqidi", "Abdulelah Alamri", "Saud Abdulhamid", "Yasser Alshahrani", "Ali Lajami", "Moteb Alharbi", "Hassan Tambakti", "Ali Albulayhi", "Ziyad Aljohani", "Abdulelah Almalki", "Mukhtar Ali", "Teamfoto (KSA)", "Ali Alhasan", "Marwan Alsahafi", "Salem Aldawsari", "Abdulrahman Ghareeb", "Firas Alburaikan", "Saleh Alshehri", "Abdullah Alhamddan"] },

    // POULE I
    { prefix: 'FRA', name: 'Frankrijk', count: 20, page: '72-73', flagUrl: 'https://flagcdn.com/w160/fr.png', colors: ['#002395', '#ED2939'], group: 'Poule I', players: ["Team Logo (Foil)", "Mike Maignan", "Théo Hernández", "William Saliba", "Jules Koundé", "Ibrahima Konaté", "Dayot Upamecano", "Lucas Digne", "Aurélien Tchouaméni", "Eduardo Camavinga", "Manu Koné", "Adrien Rabiot", "Teamfoto (FRA)", "Michael Olise", "Ousmane Dembélé", "Bradley Barcola", "Moussa Diaby", "Kingsley Coman", "Hugo Ekitiké", "Kylian Mbappé"] },
    { prefix: 'SEN', name: 'Senegal', count: 20, page: '74-75', flagUrl: 'https://flagcdn.com/w160/sn.png', colors: ['#00853F', '#FDEF42'], group: 'Poule I', players: ["Team Logo (Foil)", "Edouard Mendy", "Seny Dieng", "Moussa Niakhaté", "Abdoulaye Seck", "Ismail Jakobs", "El Hadji Malick Diouf", "Kalidou Koulibaly", "Idrissa Gana Gueye", "Pape Matar Sarr", "Pathé Ciss", "Habib Diarra", "Teamfoto (SEN)", "Lamine Camara", "Sadio Mané", "Ismaila Sarr", "Boulaye Dia", "Iliman Ndiaye", "Nicolas Jackson", "Krépin Diatta"] },
    { prefix: 'IRQ', name: 'Irak', count: 20, page: '76-77', flagUrl: 'https://flagcdn.com/w160/iq.png', colors: ['#CE1126', '#007A3D'], group: 'Poule I', players: ["Team Logo (Foil)", "Jalal Hassan", "Rebin Sulaka", "Hussein Ali", "Saad Natiq", "Merchas Doski", "Zaid Tahseen", "Manaf Younis", "Zidane Iqbal", "Amir Al-Ammari", "Bashar Resan", "Ali Jasim", "Teamfoto (IRQ)", "Youssef Amyn", "Amjad Attwan", "Ibrahim Bayesh", "Osama Rashid", "Ali Al-Hamadi", "Aymen Hussein", "Mohanad Ali"] },
    { prefix: 'NOR', name: 'Noorwegen', count: 20, page: '80-81', flagUrl: 'https://flagcdn.com/w160/no.png', colors: ['#BA0C2F', '#00205B'], group: 'Poule I', players: ["Team Logo (Foil)", "Ørjan Nyland", "Julian Ryerson", "Leo Østigård", "Kristoffer Ajer", "Marcus Holmgren Pedersen", "David Møller Wolfe", "Torbjørn Heggem", "Morten Thorsby", "Martin Ødegaard", "Sander Berge", "Andreas Schjelderup", "Teamfoto (NOR)", "Patrick Berg", "Erling Haaland", "Alexander Sørloth", "Aron Dønnum", "Jørgen Strand Larsen", "Antonio Nusa", "Oscar Bobb"] },

    // POULE J
    { prefix: 'ARG', name: 'Argentinië', count: 20, page: '82-83', flagUrl: 'https://flagcdn.com/w160/ar.png', colors: ['#74ACDF', '#D4AF37'], group: 'Poule J', players: ["Team Logo (Foil)", "Emiliano Martínez", "Nahuel Molina", "Cristian Romero", "Nicolás Otamendi", "Nicolás Tagliafico", "Leonardo Balerdi", "Enzo Fernández", "Alexis Mac Allister", "Rodrigo De Paul", "Exequiel Palacios", "Leandro Paredes", "Teamfoto (ARG)", "Nico Paz", "Franco Mastantuono", "Nico González", "Lionel Messi", "Lautaro Martínez", "Julián Álvarez", "Giuliano Simeone"] },
    { prefix: 'ALG', name: 'Algerije', count: 20, page: '84-85', flagUrl: 'https://flagcdn.com/w160/dz.png', colors: ['#006233', '#D21034'], group: 'Poule J', players: ["Team Logo (Foil)", "Alexis Guendouz", "Ramy Bensebaini", "Youcef Atal", "Rayan Aït-Nouri", "Mohamed Amine Tougai", "Aïssa Mandi", "Ismaël Bennacer", "Houssem Aouar", "Hicham Boudaoui", "Ramiz Zerrouki", "Nabil Bentaleb", "Teamfoto (ALG)", "Farès Chaïbi", "Riyad Mahrez", "Saïd Benrahma", "Anis Hadj-Moussa", "Amine Gouiri", "Baghdad Bounedjah", "Mohamed Amoura"] },
    { prefix: 'AUT', name: 'Oostenrijk', count: 20, page: '86-87', flagUrl: 'https://flagcdn.com/w160/at.png', colors: ['#ED2939', '#222222'], group: 'Poule J', players: ["Team Logo (Foil)", "Alexander Schlager", "Patrick Pentz", "David Alaba", "Kevin Danso", "Philipp Lienhart", "Stefan Posch", "Phillipp Mwene", "Alexander Prass", "Xaver Schlager", "Marcel Sabitzer", "Konrad Laimer", "Teamfoto (AUT)", "Florian Grillitsch", "Nicolas Seiwald", "Romano Schmid", "Patrick Wimmer", "Christoph Baumgartner", "Michael Gregoritsch", "Marko Arnautović"] },
    { prefix: 'JOR', name: 'Jordanië', count: 20, page: '88-89', flagUrl: 'https://flagcdn.com/w160/jo.png', colors: ['#CE1126', '#000000'], group: 'Poule J', players: ["Team Logo (Foil)", "Yazeed Abulaila", "Ihsan Haddad", "Mohammad Abu Hashish", "Yazan Al-Arab", "Abdallah Nasib", "Saleem Obaid", "Mohammad Abualnadi", "Ibrahim Saadeh", "Nizar Al-Rashdan", "Noor Al-Rawabdeh", "Mohammad Abu Taha", "Teamfoto (JOR)", "Amer Jamous", "Musa Al-Taamari", "Yazan Al-Naimat", "Mahmoud Al-Mardi", "Ali Olwan", "Mohammad Abu Zrayq", "Ibrahim Sabra"] },

    // POULE K
    { prefix: 'POR', name: 'Portugal', count: 20, page: '90-91', flagUrl: 'https://flagcdn.com/w160/pt.png', colors: ['#ED2939', '#006600'], group: 'Poule K', players: ["Team Logo (Foil)", "Diogo Costa", "José Sá", "Rúben Dias", "João Cancelo", "Diogo Dalot", "Nuno Mendes", "Gonçalo Inácio", "Bernardo Silva", "Bruno Fernandes", "João Neves", "Vitinha", "Teamfoto (POR)", "João Palhinha", "Cristiano Ronaldo", "Francisco Trincão", "João Félix", "Gonçalo Ramos", "Pedro Neto", "Rafael Leão"] },
    { prefix: 'COD', name: 'Congo-Kinshasa', count: 20, page: '92-93', flagUrl: 'https://flagcdn.com/w160/cd.png', colors: ['#007FFF', '#F7D417'], group: 'Poule K', players: ["Team Logo (Foil)", "Lionel Mpasi", "Aaron Wan-Bissaka", "Axel Tuanzebe", "Arthur Masuaku", "Chancel Mbemba", "Joris Kayembe", "Charles Pickel", "Ngal'ayel Mukau", "Edo Kayembe", "Samuel Moutoussamy", "Noah Sadiki", "Teamfoto (COD)", "Théo Bongonda", "Meschack Elia", "Yoane Wissa", "Brian Cipenga", "Fiston Mayele", "Cédric Bakambu", "Nathanaël Mbuku"] },
    { prefix: 'UZB', name: 'Oezbekistan', count: 20, page: '94-95', flagUrl: 'https://flagcdn.com/w160/uz.png', colors: ['#0099B5', '#1EB53A'], group: 'Poule K', players: ["Team Logo (Foil)", "Utkir Yusupov", "Farrukh Sayfiev", "Sherzod Nasrullaev", "Umar Eshmurodov", "Husniddin Aliqulov", "Rustam Ashurmatov", "Khojiakbar Alijonov", "Abdukodir Khusanov", "Odiljon Hamrobekov", "Otabek Shukurov", "Jamshid Iskanderov", "Teamfoto (UZB)", "Azizbek Turgunboev", "Khojimat Erkinov", "Eldor Shomurodov", "Oston Urunov", "Jaloliddin Masharipov", "Igor Sergeev", "Abbosbek Fayzullaev"] },
    { prefix: 'COL', name: 'Colombia', count: 20, page: '96-97', flagUrl: 'https://flagcdn.com/w160/co.png', colors: ['#FCD116', '#CE1126'], group: 'Poule K', players: ["Team Logo (Foil)", "Camilo Vargas", "David Ospina", "Davinson Sánchez", "Yerry Mina", "Daniel Muñoz", "Johan Mojica", "Jhon Lucumí", "Santiago Arias", "Jefferson Lerma", "Kevin Castaño", "Richard Ríos", "Teamfoto (COL)", "James Rodríguez", "Juan Fernando Quintero", "Jorge Carrascal", "Jhon Arias", "Jhon Córdoba", "Luis Suárez", "Luis Díaz"] },

    // POULE L
    { prefix: 'ENG', name: 'Engeland', count: 20, page: '98-99', flagUrl: 'https://flagcdn.com/w160/gb-eng.png', colors: ['#ED2939', '#000055'], group: 'Poule L', players: ["Team Logo (Foil)", "Jordan Pickford", "John Stones", "Marc Guéhi", "Ezri Konsa", "Trent Alexander-Arnold", "Reece James", "Dan Burn", "Jordan Henderson", "Declan Rice", "Jude Bellingham", "Cole Palmer", "Teamfoto (ENG)", "Morgan Rogers", "Anthony Gordon", "Phil Foden", "Bukayo Saka", "Harry Kane", "Marcus Rashford", "Ollie Watkins"] },
    { prefix: 'CRO', name: 'Kroatië', count: 20, page: '100-101', flagUrl: 'https://flagcdn.com/w160/hr.png', colors: ['#ED1C24', '#003893'], group: 'Poule L', players: ["Team Logo (Foil)", "Dominik Livaković", "Duje Ćaleta-Car", "Joško Gvardiol", "Josip Stanišić", "Luka Vušković", "Josip Šutalo", "Kristijan Jakić", "Luka Modrić", "Mateo Kovačić", "Martin Baturina", "Lovro Majer", "Teamfoto (CRO)", "Mario Pašalić", "Petar Sučić", "Ivan Perišić", "Marco Pašalić", "Ante Budimir", "Andrej Kramarić", "Franjo Ivanović"] },
    { prefix: 'GHA', name: 'Ghana', count: 20, page: '102-103', flagUrl: 'https://flagcdn.com/w160/gh.png', colors: ['#CE1126', '#FCD116'], group: 'Poule L', players: ["Team Logo (Foil)", "Lawrence Ati-Zigi", "Tariq Lamptey", "Mohammed Salisu", "Alidu Seidu", "Alexander Djiku", "Gideon Mensah", "Caleb Ekuban", "Abdul Fatawu Issahaku", "Thomas Partey", "Salis Abdul Samed", "Kamaldeen Sulemana", "Teamfoto (GHA)", "Mohammed Kudus", "Iñaki Williams", "Jordan Ayew", "André Ayew", "Joseph Paintsil", "Osman Bukari", "Antoine Semenyo"] },
    { prefix: 'PAN', name: 'Panama', count: 20, page: '104-105', flagUrl: 'https://flagcdn.com/w160/pa.png', colors: ['#DA291C', '#002B7F'], group: 'Poule L', players: ["Team Logo (Foil)", "Orlando Mosquera", "Luis Mejía", "Fidel Escobar", "Andrés Andrade", "Michael Amir Murillo", "Eric Davis", "José Córdoba", "César Blackman", "Cristian Martínez", "Aníbal Godoy", "Adalberto Carrasquilla", "Teamfoto (PAN)", "Édgar Bárcenas", "Carlos Harvey", "Ismael Díaz", "José Fajardo", "Cecilio Waterman", "José Luis Rodríguez", "Alberto Quintero"] }
];
